"""
Data preparation: driving forcing and calibration target.

REAL DATA (what the paper used)
-------------------------------
forcing.csv  daily, one row per day, columns:
    date        YYYY-MM-DD
    tas         near-surface air temperature [degC]     <- WRF d02, 1 km, aggregated
    pr          precipitation [mm/day]                  <- WRF d02, 1 km, aggregated
    waterfrac   surface water fraction [0-1]            <- WRF-Hydro, 50 m, aggregated
    itn_cover   ITN coverage fraction [0-1]             <- KEMRI-CDC, monthly, ffilled

observations.csv  monthly, columns:
    month       YYYY-MM
    cases       reported malaria cases                  <- KEMRI-CDC PBIDS, Asembo

The KEMRI-CDC series is RESTRICTED (apply to Dr Stephen Munga, KEMRI). Until
you have it, `synthetic_siaya()` produces a structurally realistic stand-in so
the whole pipeline can be exercised.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

REQUIRED_FORCING_COLUMNS = ("tas", "pr", "waterfrac", "itn_cover")


def load_forcing(path: str | Path) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["date"]).set_index("date").sort_index()
    missing = set(REQUIRED_FORCING_COLUMNS) - set(df.columns)
    if missing:
        raise KeyError(f"forcing file missing columns: {sorted(missing)}")
    validate_forcing(df)
    return df


def load_observations(path: str | Path) -> pd.Series:
    df = pd.read_csv(path)
    if "month" not in df.columns or "cases" not in df.columns:
        raise KeyError("observations file needs columns: month, cases")
    idx = pd.PeriodIndex(df["month"].astype(str), freq="M")
    return pd.Series(df["cases"].to_numpy(float), index=idx, name="cases").sort_index()


def validate_forcing(df: pd.DataFrame) -> None:
    """Catch the forcing problems that silently ruin a calibration."""
    problems = []
    if df.index.has_duplicates:
        problems.append("duplicate dates in forcing index")
    gaps = pd.date_range(df.index.min(), df.index.max(), freq="D").difference(df.index)
    if len(gaps):
        problems.append(f"{len(gaps)} missing days (first: {gaps[0].date()})")
    if df[list(REQUIRED_FORCING_COLUMNS)].isna().any().any():
        na = df[list(REQUIRED_FORCING_COLUMNS)].isna().sum()
        problems.append(f"NaNs present: {na[na > 0].to_dict()}")
    if (df["pr"] < 0).any():
        problems.append("negative precipitation")
    if not df["waterfrac"].between(0, 1).all():
        problems.append("waterfrac outside [0, 1]")
    if not df["itn_cover"].between(0, 1).all():
        problems.append("itn_cover outside [0, 1] (use fractions, not percent)")
    if df["tas"].max() > 60 or df["tas"].min() < -10:
        problems.append("implausible temperatures (is tas in Kelvin?)")
    if problems:
        raise ValueError("Forcing validation failed:\n  - " + "\n  - ".join(problems))


def itn_coverage_series(dates: pd.DatetimeIndex) -> np.ndarray:
    """
    ITN coverage over Asembo as described in Dieng et al. (from Nyawanda 2024):
      2007          ~0.75 baseline
      2008-2011     rapid scale-up 0.75 -> 0.93
      2012 onward   plateau 0.93-0.98 with campaign pulses every 3-4 years
    """
    years = dates.year.to_numpy() + (dates.dayofyear.to_numpy() - 1) / 365.25
    cover = np.where(
        years < 2008.0, 0.75,
        np.where(
            years < 2012.0,
            0.75 + (0.93 - 0.75) * (years - 2008.0) / 4.0,
            0.93 + 0.05 * (0.5 + 0.5 * np.sin(2 * np.pi * (years - 2012.0) / 3.5)),
        ),
    )
    return np.clip(cover, 0.0, 0.99)


def synthetic_siaya(
    start: str = "2007-01-01",
    end: str = "2022-12-31",
    seed: int = 20260119,
    true_params: dict[str, float] | None = None,
) -> tuple[pd.DataFrame, pd.Series]:
    """
    Structurally realistic synthetic Siaya forcing + pseudo-observations.

    Climate follows the paper's description: bimodal rainfall (long rains
    MAM, short rains OND), 1000-1800 mm/yr, mean annual T 21-28 degC, surface
    water fraction mostly 1-3%.

    Pseudo-observations are generated by running ReducedVectri with a KNOWN
    parameter vector and adding surveillance-like noise. That makes this a
    genuine recovery test: you know the answer the GA should find.
    """
    from .model import ReducedVectri
    from .parameters import PARAMETERS

    rng = np.random.default_rng(seed)
    dates = pd.date_range(start, end, freq="D")
    doy = dates.dayofyear.to_numpy()
    n = len(dates)

    # --- temperature: annual cycle + interannual wobble + weather noise ---
    tas = (24.5
           + 2.0 * np.sin(2 * np.pi * (doy - 20) / 365.25)
           + 0.6 * np.sin(2 * np.pi * dates.year.to_numpy() / 7.0)
           + rng.normal(0, 1.1, n))

    # --- rainfall: two wet seasons, gamma-distributed wet days ------------
    long_rains = np.exp(-0.5 * ((doy - 105) / 28.0) ** 2)    # Mar-May
    short_rains = np.exp(-0.5 * ((doy - 315) / 26.0) ** 2)   # Oct-Dec
    wet_prob = np.clip(0.10 + 0.55 * long_rains + 0.45 * short_rains, 0, 0.95)
    is_wet = rng.random(n) < wet_prob
    intensity = rng.gamma(shape=1.6, scale=7.0, size=n)
    pr = np.where(is_wet, intensity, 0.0)

    # --- surface water fraction: lagged, damped response to rainfall ------
    wfrac = np.zeros(n)
    store = 0.012
    for i in range(n):
        store = store * 0.94 + pr[i] * 0.00055      # recession + recharge
        wfrac[i] = np.clip(store, 0.002, 0.20)

    forcing = pd.DataFrame(
        {"tas": tas, "pr": pr, "waterfrac": wfrac,
         "itn_cover": itn_coverage_series(dates)},
        index=dates,
    )
    forcing.index.name = "date"
    validate_forcing(forcing)

    # --- pseudo-observations from a KNOWN parameter vector ----------------
    if true_params is None:
        # Use the PUBLISHED best-fit column as ground truth, so a successful
        # calibration should recover something close to Dieng et al. Table 1.
        true_params = {
            p.symbol: (p.published_bestfit if p.published_bestfit is not None else p.default)
            for p in PARAMETERS
        }

    sim = ReducedVectri().run(true_params, forcing)
    # surveillance noise: multiplicative reporting error + additive counting noise
    noisy = sim.to_numpy(float) * rng.normal(1.0, 0.12, len(sim)) \
        + rng.normal(0, 25.0, len(sim))
    obs = pd.Series(np.clip(noisy, 0, None), index=sim.index, name="cases")
    return forcing, obs


def write_templates(outdir: str | Path) -> dict[str, Path]:
    """Emit empty CSV templates with the exact columns the pipeline expects."""
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    f = outdir / "forcing_TEMPLATE.csv"
    o = outdir / "observations_TEMPLATE.csv"
    pd.DataFrame(columns=["date", *REQUIRED_FORCING_COLUMNS]).to_csv(f, index=False)
    pd.DataFrame(columns=["month", "cases"]).to_csv(o, index=False)
    return {"forcing": f, "observations": o}
